# Generated by Django 5.2.17 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(
                help_text='Use the rich text editor to format the post body and add links or images.',
            ),
        ),
    ]