# Generated by Django 5.2.17 on 2026-08-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_dailyvisitor_visitorcountsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilentMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='movies/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'silent movie',
                'verbose_name_plural': 'silent movies',
                'ordering': ('sort_order', 'title', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('audio', models.FileField(upload_to='songs/')),
                ('effect_parameters', models.JSONField(blank=True, default=dict, help_text='Tone.js effect settings as JSON. Leave empty for a dry signal.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'title', 'pk'),
            },
        ),
    ]
