# Generated by Django 5.2.17 on 2026-08-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_silentmovie_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='silentmovie',
            name='effect_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Visual effect settings as JSON. Leave empty for the original image.'),
        ),
    ]
